# This is a basic workflow to help you get started with Actions

name: Deploy dev env

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ feature/**, fix/** ]
  pull_request:
    branches: [ feature/**, fix/** ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip ../laravel-dev-deployment-package.zip -r * .[^.]* -x "vendor/*"

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EBS_APPLICATION_NAME }}
        environment_name: ${{ secrets.EBS_ENV_NAME_DEV }}
        version_label: ${{ steps.buildnumber.outputs.BUILD_NUMBER }}
        region: eu-west-1
        deployment_package: ../laravel-dev-deployment-package.zip
